# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-24 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feature_image',
        ),
    ]
