# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-26 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auhor',
            new_name='author',
        ),
    ]
